version: '3'

services:

##################################################################
#  Reverse Proxy and SSL                                         #
##################################################################

  traefik:
    image: traefik:v2.11
    command:
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.grpc.address=:5000"
    ports:
      - "${HTTP_PORT}:80/tcp"
      - "${GRPC_PORT}:5000/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/letsencrypt:/letsencrypt"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    expose:
      - '80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    labels:
      - "traefik.enable=false"

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    expose:
      - '3000'
      - '5000'
    depends_on:
      - redis
      - identity
    volumes:
      - ./backend/src:/app/src
      - ./web/build:/web/build
      - ./proto:/proto
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  identity:
    image: identity-grpc-test:latest
    environment:
      - API_ENDPOINT=http://localhost
      - STRONGHOLD_PWD=qhNR2KaMKaGZZIrUlXWvZ8ScZiBMtQiK
      - SNAPSHOT_PATH=/stronghold.hodl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/stronghold.hodl:/stronghold.hodl"
    expose:
     - '50051'
    labels:
      - "traefik.enable=false"
