version: '3'

services:

##################################################################
#  Reverse Proxy and SSL                                         #
##################################################################

  traefik:
    image: traefik:v2.11
    command:
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.grpc.address=:5000"
    ports:
      - "${HTTP_PORT}:80/tcp"
      - "${GRPC_PORT}:5000/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/letsencrypt:/letsencrypt"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    expose:
      - '80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  
  redis:
    image: redis:latest
    labels:
      - "traefik.enable=false"

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    expose:
      - '3000'
      - '5000'
    depends_on:
      - redis
      - identity
    environment:
      ISSUERS_BANK_DID: did:iota:snd:0x1d78531b739a3aef0e90523213f28e869423a6d6253ea0fcbd7db2714e9606bf
      ISSUERS_BANK_FRAGMENT: xwhWgiK3plOzbQESCONMneeFx4ps24rzbtC1jXEb42o
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  oid4vc-tanglelabs:
    build:
      context: ./
      dockerfile: ./oid4vc/TangleLabs/Dockerfile
    expose:
      - '50051'
    volumes:
      - ./proto:/usr/proto
    labels:
      - "traefik.enable=false"

  oid4vc-waltid:
    build:
      context: ./
      dockerfile: ./oid4vc/walt.id/Dockerfile
    expose:
      - '50051'
    volumes:
      - ./proto:/usr/proto
    labels:
      - "traefik.enable=false"

  identity:
    image: identity-grpc-test:latest
    environment:
      - API_ENDPOINT=http://host.docker.internal
      - STRONGHOLD_PWD=nEyWjBDO3sQSDnXuwij3KIJREHnWhtIu
      - SNAPSHOT_PATH=/stronghold.hodl
    volumes:
      - "./data/stronghold.hodl:/stronghold.hodl"
    expose:
     - '50051'
    labels:
      - "traefik.enable=false"
