version: '3'

services:
  
  redis:
    image: redis:latest
    labels:
      traefik.enable: false

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    expose:
      - '3000'
      - '50051'
    ports:
      - "127.0.0.1:3000:3000/tcp"
    # depends_on:
    #   - redis
    #   - identity
    environment:
      ISSUERS_BANK_DID: did:iota:snd:0x2cfb60f00089a91a96fa8fcee5e2bda15f51b0b062762ad9ca846bba536f8818
      ISSUERS_BANK_FRAGMENT: S3zEW4inNy8FYZEMVTEthdzqqSBq1WglM2k75xKHzy0

  identity:
    image: iotaledger/identity-grpc:alpha
    environment:
      - API_ENDPOINT=https://api.testnet.shimmer.network
      - SNAPSHOT_PATH=/stronghold.hodl
      - STRONGHOLD_PWD_FILE=/run/secrets/stronghold_pwd
    volumes:
      - "./data/stronghold.hodl:/stronghold.hodl"
    expose:
     - '50051'
    labels:
      traefik.enable: false
    secrets:
      - stronghold_pwd

  oid4vc-tanglelabs:
    build:
      context: ./
      dockerfile: ./oid4vc/TangleLabs/Dockerfile
    environment:
      RP_DID: did:iota:snd:0x2cfb60f00089a91a96fa8fcee5e2bda15f51b0b062762ad9ca846bba536f8818
      SIGNER_KEYID: pK0JAYw5RFFKqorBn0x4w98zl2UBfRys
      KEY_FRAGMENT: key-1
      PUBLIC_URL: "bank.selv.iota.org"
    expose:
      - '3333'
      - '50051'
    ports:
      - "127.0.0.1:3333:3333/tcp"
    volumes:
      - ./proto:/usr/proto

  oid4vc-waltid:
    build:
      context: ./
      dockerfile: ./oid4vc/walt.id/Dockerfile
    expose:
      - '3000'
      - '50051'
    ports:
      - "127.0.0.1:3001:3000/tcp"
    volumes:
      - ./proto:/usr/proto

  oid4vc-impierce:
    image: impierce/ssi-agent
    expose:
      - '3033'
    ports:
      - "127.0.0.1:3033:3033/tcp"
    volumes:
      - ./proto:/usr/proto
    environment:
      #AGENT_CONFIG_LOG_FORMAT: json
      AGENT_CONFIG_EVENT_STORE: postgres
      #AGENT_CONFIG_BASE_PATH: "unicore"
      AGENT_APPLICATION_URL: ${backend}
      AGENT_STORE_DB_CONNECTION_STRING: postgresql://demo_user:demo_pass@cqrs-postgres-db:5432/demo

  cqrs-postgres-db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - "./data/db:/docker-entrypoint-initdb.d"

secrets:
  stronghold_pwd:
    file: data/stronghold_secret.txt
